obj-m += platform_driver2.o
all:
	make -C /home/sice/kj_gjx_embedd_base/lab_8/linux-3.5 M=`pwd` modules
#	cp platform_driver.ko /opt/rootfs/lib/modules/3.5.0cyh/lab8_platform_module/platform_driver.ko
clean:
	make -C /home/sice/kj_gjx_embedd_base/lab_8/linux-3.5 M=`pwd` modules clean
