obj-m += platform_device2.o
all:
	make -C /home/sice/kj_gjx_embedd_base/lab_8/linux-3.5 M=`pwd` modules
#	cp platform_device.ko /opt/rootfs/lib/modules/3.5.0cyh/lab8_platform_module/platform_device.ko
clean:
	make -C /home/sice/kj_gjx_embedd_base/lab_8/linux-3.5 M=`pwd` modules clean
